{
 "title": "Jutjubić Monitoring",
 "time": { "from": "2026-02-16T19:03:37.151Z", "to": "2026-02-16T19:05:30.993Z" },
 "panels": [
  {
   "title": "Aktivni korisnici u 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_active_users_24h", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Zauzeće",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB Konekcije",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "hikaricp_connections_active", "legendFormat": "__auto" },
    { "expr": "hikaricp_connections_idle", "legendFormat": "__auto" }
   ]
  }
 ]
}